ports:
  - '8125:8125/udp'

directories:
  - /data/statsd

files: [
  {src: 'statsd-config.ctmpl', dest: '/data/consul-template/statsd-config.ctmpl'},
]

volumes:
  - /data/statsd/config.js:/statsd/config.js
