databases:
  - statsite
  - collectd

ports:
  - '8083:8083' 
  - '8086:8086'
  - '25826:25826/udp'

directories:
  - /data/influxdb

files: [
  {src: 'influxdb_1.1.1.conf', dest: '/data/influxdb/influxdb.conf'},
  {src: 'types.db', dest: '/data/influxdb/types.db'}
]

volumes:
  - /data/influxdb:/var/lib/influxdb
  - /data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
  - /data/influxdb/types.db:/usr/share/collectd/types.db
