databases:
  - statsd
  - collectd

ports:
  - '8083:8083' 
  - '8086:8086'
  - '25826:25826/udp'

directories:
  - /data/influxdb/etc

files: [
  {src: 'influxdb.conf', dest: '/data/influxdb/influxdb.conf'}
]

volumes:
  - /data/influxdb:/var/lib/influxdb
  - /data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
