- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
    owner: vagrant
  with_items: "{{ directories }}"
  tags: [haproxy]

- name: Files are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ files }}"
  register: result
  tags: [haproxy]

# Haproxy has no reload signal handling, we use its customized feature so it will reload automatically if it's running there
# (based on inotify mechanism)
- name: Config haproxy.conf is generated based on data in consul and template
  shell: "consul-template -once \
          -template '/data/consul-template/haproxy.ctmpl:/data/haproxy/config/haproxy.cfg.append' \
          -consul {{ consul_master_address }} && \
          cat /data/haproxy/config/haproxy.cfg.orig /data/haproxy/config/haproxy.cfg.append > /data/haproxy/config/haproxy.cfg"
  tags: [haproxy]

- name: Container is running
  docker_container:
    image: million12/haproxy # Not use the official image here because this image support automatic reload based on inotify mechanim, while official one need restart
    name: haproxy
    state: started
    ports: "{{ ports }}"
    volumes: /data/haproxy/config/:/etc/haproxy/
  tags: [haproxy]
