- hosts: prod
  remote_user: vagrant
  sudo: yes
  vars:
    debian_version: trusty
  tasks:
    # JQ
    - name: JQ is present
      apt:
        name: jq
        force: yes

    # Docker
    - name: Debian add Docker repository and update apt cache
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-{{ debian_version }} main
        update_cache: yes
        state: present

    - name: Debian Docker is present
      apt:
        name: docker-engine
        state: latest
        force: yes

    - name: vagrant user is added to the docker group
      user:
        name: vagrant
        group: docker
      register: user_result

    - name: Debian python-pip is present
      apt:
        name: python-pip
        state: present
        force: yes

    - name: Debian docker-py is present
      pip:
        name: docker-py
        version: 1.6.0
        state: present

    - name: DockerUI is running
      docker:
        image: uifd/ui-for-docker
        name: dockerui
        ports: 9000:9000
        privileged: yes
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
      when: not skip_ui is defined

    # Application
    - name: Store service is running
      docker:
        name: StoreService
        ports: 8001:8001
        image: yinc2/store-service:latest
        state: started
      tags: [store]
    - name: Fibonacci service is running
      docker:
        name: FibonacciService
        ports: 8888:8888
        image: yinc2/fibonacci-web-service:latest
        state: started
