zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - 2181:2181

kafka:
  image: wurstmeister/kafka:0.9.0.0-1
  ports:
    - 9092:9092
    - 1099:1099
  links:
    - zookeeper:zk
  environment:
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_BROKER_ID=1
    - KAFKA_CREATE_TOPICS=test:3:1
    - KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.33.22 -Dcom.sun.mana    gement.jmxremote.rmi.port=1099"
    - JMX_PORT: 1099
