cassandra1:
    image: cassandra:2.2.8
    ports:
        - 9042:9042 

cassandra2:
    image: cassandra:2.2.8
    ports:
        - 9043:9042
    environment:
        - CASSANDRA_SEEDS=cassandra1
    links:
        - "cassandra1"

cassandra3:
    image: cassandra:2.2.8
    ports:
        - 9044:9042 
    environment:
        - CASSANDRA_SEEDS=cassandra1
    links:
        - "cassandra1"
