ports:
  - '8000:80'

directories:
  - /data/haproxy/config

files: [
  {src: 'haproxy.cfg.orig', dest: '/data/haproxy/config/haproxy.cfg.orig'},
  {src: 'haproxy.ctmpl', dest: '/data/consul-template/haproxy.ctmpl'}
]
