- hosts: elk
  remote_user: vagrant
  become: true
  roles:
    - elasticsearch
    - logstash
    - fluentd
    - kibana

- hosts: yinc2-cluster
  remote_user: vagrant
  become: true
  roles:
    - rsyslog

