# Alernative solution for consul+register+consul-template in terms of service registery and discovery,
# and configuration key-value store.
- hosts: service-registry-discovery-config-mgmt
  remote_user: vagrant
  become: true
  roles:
    - common
    - docker
    - etcd
    - registrator
    - confd
